function SDR = sdr_initial(config, mode)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%   Transmitter initialization   %%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if strcmp('transmitter', mode)

    switch config.sdr.type
        case 'n210' % Create USRP SDR receiver
        
        address = '192.168.10.2'; % IP address of the USRP
        platform = 'N200/N210/USRP2';
        
        % Baseband sample rate = Master clock rate/Decimation factor
        MasterClockRate = 100e6; % default 100 MHz for n210
        USRPInterpolationFactor = MasterClockRate/config.sdr.FrontEndSampleRate;

        SDR = comm.SDRuTransmitter(...
            'Platform',             platform, ...
            'IPAddress',            address, ...
            'CenterFrequency',      config.sdr.fc, ...
            'Gain',                 config.sdr.tx_gain, ...
            'InterpolationFactor',  USRPInterpolationFactor);
        
        % factor = 40 + config.sdr.gain;

        case {'b200', 'b210', 'b200_mini'} % Create USRP SDR receiver
            
            sdr_info = findsdru();
            serialNum = sdr_info.SerialNum; % IP address of the USRP
            platform = sdr_info.Platform;
            
            % Baseband sample rate = Master clock rate/Decimation factor
            MasterClockRate = 32e6; % default 32 MHz for b200
            USRPInterpolationFactor = MasterClockRate/config.sdr.FrontEndSampleRate;

            SDR = comm.SDRuTransmitter(...
                'Platform',  platform, ...
                'SerialNum', serialNum,...
                'CenterFrequency',      config.sdr.fc, ...
                'Gain',                 config.sdr.tx_gain, ...
                'InterpolationFactor',  USRPInterpolationFactor);
            
            % factor = 40 + config.sdr.gain;
    
        case 'pluto' 
           
           SDR = comm.SDRTxPluto(...
                 'RadioID','usb:0',...
                 'CenterFrequency',config.sdr.fc, ...
                 'BasebandSampleRate',config.sdr.FrontEndSampleRate,...
                 'Gain', config.sdr.tx_gain,...
                 'ShowAdvancedProperties', true);
           
             % factor = 25 + config.sdr.gain;


        otherwise
            error('Initialization failed. Undefined SDR Type!')
    end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%   Receiver initialization   %%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

elseif strcmp('receiver', mode)

    switch config.sdr.type
        case 'rtl'  % Create RTL SDR receiver
            
            SDR = comm.SDRRTLReceiver(...
                'CenterFrequency', config.sdr.fc, ...
                'EnableTunerAGC',  false, ...
                'TunerGain',    config.sdr.rx_gain,...
                'SampleRate',      config.sdr.FrontEndSampleRate, ...
                'SamplesPerFrame', config.FrameLength, ...
                'OutputDataType',  'double');
            %                 fprintf('sdr init\n');
            % factor = 0;
        case 'n210' % Create USRP SDR receiver
            
            address = '192.168.10.2'; % IP address of the USRP
            platform = 'N200/N210/USRP2';

            MasterClockRate = 100e6; % 100 MHz
            % Baseband sample rate = Master clock rate/Decimation factor
            USRPDecimationFactor = MasterClockRate/config.sdr.FrontEndSampleRate;
            
            SDR = comm.SDRuReceiver(...
                'Platform',             platform, ...
                'IPAddress',            address, ...
                'CenterFrequency',      config.sdr.fc, ...
                'Gain',                 config.sdr.rx_gain, ...
                'DecimationFactor',     USRPDecimationFactor, ...
                'SamplesPerFrame',      config.sdr.FrameLength, ...
                'MasterClockRate',      MasterClockRate, ...
                'OutputDataType',       'double');
            
            % factor = 40 + config.sdr.gain;
            
        case {'b200', 'b210', 'b200_mini'} % Create USRP SDR receiver
            
            sdr_info = findsdru();
            serialNum = sdr_info.SerialNum; % IP address of the USRP
            platform = sdr_info.Platform;
            MasterClockRate = 32e6; % default 32 MHz
            % Baseband sample rate = Master clock rate/Decimation factor
            USRPDecimationFactor = MasterClockRate/config.sdr.FrontEndSampleRate;
    %         USRPDecimationFactor = 50; 
            
            SDR = comm.SDRuReceiver(...
                'Platform',  platform, ...
                'SerialNum', serialNum,...
                'CenterFrequency',      config.sdr.fc, ...
                'Gain',                 config.sdr.rx_gain, ...
                'DecimationFactor',     USRPDecimationFactor, ...
                'SamplesPerFrame',      config.sdr.FrameLength, ...
                'MasterClockRate',      MasterClockRate, ...
                'OutputDataType',       'double');
            
            % factor = 40 + config.sdr.gain;
    
        case 'pluto' 
           
           SDR = comm.SDRRxPluto(...
                 'RadioID','usb:0',...
               'CenterFrequency',config.sdr.fc, ...
               'BasebandSampleRate',config.sdr.FrontEndSampleRate,...
               'GainSource', 'Manual',...
               'Gain', config.sdr.rx_gain,...
               'ShowAdvancedProperties', true, ...
               'EnableRFDCCorrection', true, ...
               'EnableBasebandDCCorrection', true, ...
               'EnableQuadratureCorrection', true, ...
               'SamplesPerFrame', config.sdr.FrameLength, ...
               'OutputDataType','double');
           
            % 'Gain', config.sdr.rx_gain,...
           
             % factor = 25 + config.sdr.gain;
        
        case 'zedboard'     
            SDR = comm.SDRRxAD936x(...
               'IPAddress','192.168.3.2',...
               'CenterFrequency',config.sdr.fc, ...
               'BasebandSampleRate',config.sdr.FrontEndSampleRate,...
               'GainSource', 'Manual',...
               'Gain', config.sdr.rx_gain,...
               'ShowAdvancedProperties', true, ...
               'SamplesPerFrame', config.sdr.FrameLength, ...
               'OutputDataType','double');
           
             % factor = 25 + config.sdr.gain;

        otherwise
            error('Initialization failed. Undefined SDR Type!')
            
    end

end

end

